<div id="myCarousel" class="carousel slide hidden-phone">
      <div class="carousel-inner">
        <div class="item">
          <img src="<?= $this->baseUrl()?>/img/slide-01.jpg" alt="">
          <div class="container">
            <div class="carousel-caption">
              <h1>Example headline.</h1>
              <p class="lead">Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
              <a class="btn btn-large btn-primary" href="#">Sign up today</a>
            </div>
          </div>
        </div>
        <div class="item active">
          <img src="<?= $this->baseUrl()?>/img/slide-02.jpg" alt="">
          <div class="container">
            <div class="carousel-caption">
              <h1>Another example headline.</h1>
              <p class="lead">Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
              <a class="btn btn-large btn-primary" href="#">Learn more</a>
            </div>
          </div>
        </div>
        <div class="item">
          <img src="<?= $this->baseUrl()?>/img/slide-03.jpg" alt="">
          <div class="container">
            <div class="carousel-caption">
              <h1>One more for good measure.</h1>
              <p class="lead">Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
              <a class="btn btn-large btn-primary" href="#">Browse gallery</a>
            </div>
          </div>
        </div>
      </div>
      <a class="left carousel-control" href="#myCarousel" data-slide="prev">‹</a>
      <a class="right carousel-control" href="#myCarousel" data-slide="next">›</a>
</div>
</div>
<div class="spacer hidden-desktop"></div>
<div class="container">
<video width="260" height="260" controls>
<source src="http://distilleryimage7.s3.amazonaws.com/c69c87de3d2811e3b34b22000aaa2162_102.mp4" type="video/mp4">
Your browser does not support the video tag.
</video>
        <div class="row">
			                <div class="span11 offset1">
                        <?php foreach($this->data['data'] as $profileinfo){
                        	              echo '<div class="span3 well well-small card">';
                        	                     if($profileinfo['type'] == "video"){
                        	                     	echo '<video width="260" height="260" controls>'.
                          	                     	     '<source src="'.$profileinfo['videos']['low_resolution']['url'].'" type="video/mp4">'.
                          	                     	     'Your browser does not support the video tag.'.
                          	                     	     '</video>'.
                        	                     	     '<a href="'.SITE_ROOT.'/view/profile/'.$profileinfo['user']['id'].'">';
                        	                     }else{
                        	                     	echo '<a href="'.SITE_ROOT.'/view/profile/'.$profileinfo['user']['id'].'">'.
                        	                     		 '<img src="'.$profileinfo['images']['standard_resolution']['url'].'" width="260px" class="img-polaroid">';
                        	                     }
                                                 
                                          echo '</a><br/>'.
												 '<a href="'.SITE_ROOT.'/view/profile/'.$profileinfo['user']['id'].'">'.
												 	'<h5>@'.$profileinfo['user']['username'].'</h5>'.
												 '</a>'.
												 '<h5>Likes: '.$profileinfo['likes']['count'].'</h5>';
                                          echo (isset($profileinfo['caption'])&&isset($profileinfo['caption']['text'])) ? $profileinfo['caption']['text'] :NULL ;
                                          echo '</div>';
                        }?>
                       
        </div>
<!--<pre>
<?php print_r($this->data['data']);?>
</pre>-->
		</div>
</div>
<div class="spacer"></div>
