<br>
<br>
<br>
<br>
<div id="myCarousel" class="carousel slide hidden-phone">
      <div class="carousel-inner">
        <div class="item active">
          <img src="<?= $this->baseUrl()?>/img/ciroc-banner.jpg" alt="">
        </div>
        <div class="item">
          <img src="<?= $this->baseUrl()?>/img/hip-hop-fest-banner.png" alt="">
        </div>
        <div class="item">
          <img src="<?= $this->baseUrl()?>/img/lhh_banner.png" alt="">
        </div>
      </div>
      <a class="left carousel-control" href="#myCarousel" data-slide="prev">‹</a>
      <a class="right carousel-control" href="#myCarousel" data-slide="next">›</a>
</div>

<div class="spacer hidden-desktop"></div>
<div class="container">
<ul class="pager">
  <li><a href="#">Previous</a></li>
  <li><a href="#">Next</a></li>
</ul>
        <div class="row">
			                <div class="span11 offset1">
                        <?php foreach($this->data['data'] as $profileinfo){
                        	              echo '<div class="span3 well well-small card">';
                        	                     if($profileinfo['type'] == "video"){
                        	                     	echo '<video width="260" height="260" controls>'.
                          	                     	     '<source src="'.$profileinfo['videos']['low_resolution']['url'].'" type="video/mp4">'.
                          	                     	     'Your browser does not support the video tag.'.
                          	                     	     '</video>'.
                        	                     	     '<a href="'.SITE_ROOT.'/view/profile/'.$profileinfo['user']['id'].'">';
                        	                     }else{
                        	                     	echo '<a href="'.SITE_ROOT.'/view/profile/'.$profileinfo['user']['id'].'">'.
                        	                     		 '<img src="'.$profileinfo['images']['standard_resolution']['url'].'" width="260px" class="img-polaroid">';
                        	                     }
                                                 
                                          echo '</a><br/>'.
												 '<a href="'.SITE_ROOT.'/view/profile/'.$profileinfo['user']['id'].'">'.
												 	'<h5>@'.$profileinfo['user']['username'].'</h5>'.
												 '</a>'.
												 '<h5>Likes: '.$profileinfo['likes']['count'].'</h5>';
                                          echo (isset($profileinfo['caption'])&&isset($profileinfo['caption']['text'])) ? $profileinfo['caption']['text'] :NULL ;
                                          echo '</div>';
                        }?>
                       
        </div>
<!--<pre>
<?php print_r($this->data['data']);?>
</pre>-->
		</div>
<ul class="pager">
  <li><a href="#">Previous</a></li>
  <li><a href="#">Next</a></li>
</ul>
</div>
<div class="spacer"></div>
