<div id="myCarousel" class="carousel slide">
      <div class="carousel-inner">
        <div class="item">
          <img src="<?= $this->baseUrl()?>/img/slide-01.jpg" alt="">
          <div class="container">
            <div class="carousel-caption">
              <h1>Example headline.</h1>
              <p class="lead">Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
              <a class="btn btn-large btn-primary" href="#">Sign up today</a>
            </div>
          </div>
        </div>
        <div class="item active">
          <img src="<?= $this->baseUrl()?>/img/slide-02.jpg" alt="">
          <div class="container">
            <div class="carousel-caption">
              <h1>Another example headline.</h1>
              <p class="lead">Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
              <a class="btn btn-large btn-primary" href="#">Learn more</a>
            </div>
          </div>
        </div>
        <div class="item">
          <img src="<?= $this->baseUrl()?>/img/slide-03.jpg" alt="">
          <div class="container">
            <div class="carousel-caption">
              <h1>One more for good measure.</h1>
              <p class="lead">Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
              <a class="btn btn-large btn-primary" href="#">Browse gallery</a>
            </div>
          </div>
        </div>
      </div>
      <a class="left carousel-control" href="#myCarousel" data-slide="prev">‹</a>
      <a class="right carousel-control" href="#myCarousel" data-slide="next">›</a>
    </div>
    <br /><br />
<div class="container-fluid">
	<div class="row">
		<div class="span12">
			<?php foreach($this->data['data'] as $profileinfo){
					echo '<div class="well well-small span3 card">'.
						 '<a href="http://www.toohotforig.com/view/profile/'.$profileinfo['user']['id'].'">'.
						 '<img src="'.$profileinfo['images']['standard_resolution']['url'].'" width="200px" class="img-polaroid">'.
						 '</a><br/>
              			  <a href="http://www.toohotforig.com/view/profile/'.$profileinfo['user']['id'].'"><h5>'.$profileinfo['user']['username'].'</h5></a>
              			  <h5>Likes: '.$profileinfo['likes']['count'].'</h5>';
						  echo (isset($profileinfo['caption'])&&isset($profileinfo['caption']['text'])) ? $profileinfo['caption']['text'] : "" ;
						  echo '</div>';
			}?>
			</div>
	</div>
<pre>
<?php print_r($this->data['data']);?>
</pre>
</div>