
<br /><br />
<br>
<br>
<br>
<br>
<div class="container-fluid">
<?php 
echo '<h2>'.$this->data['data'][0]['user']['full_name'].'</h2>'.
	 '<h5> @'.$this->data['data'][0]['user']['username'].'</h5>';
?>
	<div class="row-fluid">
		<div class="span12">
			<?php foreach($this->data['data'] as $profileinfo){
					echo '<div class="well well-small pull-right">'.
						 '<a href="'.SITE_ROOT.'/view/profile/'.$profileinfo['user']['id'].'">'.
						 '<img src="'.$profileinfo['images']['standard_resolution']['url'].'" width="200px" class="img-polaroid">'.
						 '</a></div>';
			}?>
			</div>
	</div>
<pre>
<?php print_r($this->data['data'][0]);?>
</pre>
</div>