<br>
<br>
<br>
<div class="container">
  <div class="media offset1">
    <a class="pull-left">
      <img class="media-object" src="<?php echo $this->data['data'][0]['user']['profile_picture'];?>" width="90" height="90">
    </a>
    <div class="media-body">
      <h4 class="media-heading"><?php echo $this->data['data'][0]['user']['full_name'];?></h4>
      <?php echo '<h5> @'.$this->data['data'][0]['user']['username'].'</h5>';?>
      <button type="button" class="btn btn-mini btn-success">Follow</button>
    </div>
  </div>
<?= $this->render('elements/pagination.phtml');?>
<?= $this->render('elements/posts.phtml');?>
<?= $this->render('elements/pagination.phtml');?>
</div>